export const RECEIVE_NEW_ARTICLE = 'HOME/RECEIVE_NEW_ARTICLE'
export const EDIT_ARTICLE = 'HOME/EDIT_ARTICLE'
export const REMOVE_ARTICLE = 'HOME/REMOVE_ARTICLE'
export const CHANGE_FAV = 'HOME/CHANGE_FAV'